### ISSUE TITLE
Use `shopify/oxygenctl-action@main` in Oxygen Workflow

### ISSUE THREAD

**Issue by eggiepiggie** [Shopify/oxygenctl-action#12]
Instead of always re-releasing our GitHub action for the [Oxygen workflow](https://github.com/Shopify/shopify/blob/f940674e7bb2de3d19730634feef06b100d016eb/components/online_store/app/services/online_store/version_control/custom_storefront_github_installation_service.rb#L138-L143), we can have our workflow point to the `main` (default branch) instead of `v1`. So this step in our Oxygen workflow would like this:

```yaml
# Publish to Oxygen
- name: Publish
  id: deploy
  uses: shopify/oxygenctl-action@main # Note the default branch name
  with:
    oxygen_deployment_token: ${{ secrets.OXYGEN_DEPLOYMENT_TOKEN }}
```

This would mean we can skip the [re-releasing](https://github.com/Shopify/oxygenctl-action/blob/main/RELEASING.md) step every time we make a change to our action.  This would go the same for [github-deployment-action](https://github.com/Shopify/github-deployment-action).

GitHub Reference: [Public Actions](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-using-a-public-action)
