### ISSUE TITLE
github.event.head_commit not available on pull_request events

### ISSUE THREAD

**Issue by kcarra** [Shopify/oxygenctl-action#35]
Currently the `shopify/oxygenctl-action` action expects a `commit_message` and `commit_timestamp` input. This works fine if you are using an on `push` GH action event. However, in our case we are trying to trigger an Oxygen build and deploy on `pull_request`. In this case `github.event.head_commit.message` and `github.event.head_commit.timestamp` are not present. The error that we are seeing in the action logs is `commit message is missing` As a work around I have tried to do something like this: 
```
    - name: Output commit msg and timestamp
      id: commit_msg_timestamp
      run: |
        message=$(git log -1 --format=oneline --pretty=format:"%s")
        timestamp=$(git log -1 --format=%cd --date=local)
        echo "::set-output name=commit_message::$message"
        echo "::set-output name=commit_timestamp::$timestamp"

  steps:
    - name: Build and Publish to Oxygen
      id: deploy
      uses: shopify/oxygenctl-action@v4
      with:
        oxygen_deployment_token: ${{ secrets.OXYGEN_DEPLOYMENT_TOKEN_239 }}
        build_command: 'HYDROGEN_ASSET_BASE_URL=$OXYGEN_ASSET_BASE_URL yarn build'
        commit_message: ${{ steps.commit_msg_timestamp.outputs.commit_message }}
        commit_timestamp: ${{ steps.commit_msg_timestamp.outputs.commit_timestamp }}

    - name: Create GitHub Deployment
      uses: shopify/github-deployment-action@v1
      if: always()
      with:
        token: ${{ github.token }}
        environment: 'preview'
        preview_url: ${{ steps.deploy.outputs.url }}
        description:${{ steps.commit_msg_timestamp.outputs.commit_message }}
```
This works fine with the `commit_message` input as it seems to just want any arbitrary string. However this does still break the timestamp. The github actions logs looks like this `invalid datetime value Tue Aug 9 18:46:27 2022` I used the same git command that was recommended in this issue https://github.com/Shopify/oxygenctl-action/issues/16. Not sure if this can be changed to loosen the timestamp validation, if i'm just doing this wrong, or if there's a better way to pass a valid timestamp
