### ISSUE TITLE
ReferenceError: Oxygen is not defined

### ISSUE THREAD

**Issue by jonasivy** [Shopify/oxygenctl-action#36]
I'm having error on Github actions, but it's running smoothly when trying to build on local.

```
- name: Build and Publish to Oxygen
  id: deploy
  uses: shopify/oxygenctl-action@v4
  with:
    oxygen_deployment_token: ${{ secrets.OXYGEN_DEPLOYMENT_TOKEN }}
    build_command: "HYDROGEN_ASSET_BASE_URL=$OXYGEN_ASSET_BASE_URL yarn build"
```

```
🚀 Uploading deployment files... 
🛑 InvalidScriptError: retrying will not succeed. The following error must be actioned:

Uncaught ReferenceError: Oxygen is not defined
  at worker.mjs:113:854
Error: Process completed with exit code 1.
```
