### ISSUE TITLE
ReferenceError: module is not defined

### ISSUE THREAD

**Issue by bgonzalez-thestable** [Shopify/oxygenctl-action#37]
Currently facing an issue on Github actions:

```
- name: Build and Publish to Oxygen
  id: deploy
  uses: shopify/oxygenctl-action@v4
  with:
    oxygen_deployment_token: ${{ secrets.OXYGEN_DEPLOYMENT_TOKEN }}
    build_command: "HYDROGEN_ASSET_BASE_URL=$OXYGEN_ASSET_BASE_URL yarn build"
```

```
🚀 Uploading deployment files... 
🛑 InvalidScriptError: retrying will not succeed. The following error must be actioned:

Uncaught ReferenceError: module is not defined
  at worker.mjs:319:11321
Error: Process completed with exit code 1.
```

The `yarn build` / `yarn preview` commands run without errors locally.
