### ISSUE TITLE
Error: Deployment to Oxygen failed. Check the 'Build and Publish to Oxygen' step for more information. 

### ISSUE THREAD

**Issue by paineleffler** [Shopify/oxygenctl-action#56]
Github action fails to deploy with the following `.yml` and logs.

Here's the section in the `oxygen-deployment-######.yml` file
```
      - name: Build and Publish to Oxygen
        id: deploy
        uses: shopify/oxygenctl-action@v4
        with:
          oxygen_deployment_token: ${{ secrets.OXYGEN_DEPLOYMENT_TOKEN_###### }}
          build_command: "HYDROGEN_ASSET_BASE_URL=$OXYGEN_ASSET_BASE_URL yarn build"
```

Create Github Deployment
```
Run shopify/github-deployment-action@v1
Error: Deployment to Oxygen failed. Check the 'Build and Publish to Oxygen' step for more information.
```

Build and Publish to Oxygen 

`🚀 Uploading deployment... `
...
`✅ Done in 4.40s.`
...
```
📡 Checking deployment... 
🔁 Trying again in 5s...
🔁 Trying again in 10s...
🔁 Trying again in 15s...
🔁 Trying again in 30s...
🔁 Trying again in 1m0s...
🤕 The deployment was uploaded but cannot be reached yet.
```

After chatting with support I was able to get around this, by adding `oxygen_health_check: false`. Is this the recommended route to fix this or is there another issue that is causing this?

```
      - name: Build and Publish to Oxygen
        id: deploy
        uses: shopify/oxygenctl-action@v4
        with:
          oxygen_deployment_token: ${{ secrets.OXYGEN_DEPLOYMENT_TOKEN_###### }}
          build_command: "HYDROGEN_ASSET_BASE_URL=$OXYGEN_ASSET_BASE_URL yarn build"
          oxygen_health_check: false
```

Thanks!
