### ISSUE TITLE
Don't use magic comments - pass the storefront ID as parameter

### ISSUE THREAD

**Issue by magnattic** [Shopify/oxygenctl-action#63]
I just stumbled hard across this problem:

Why are you using magic comments at the top of the workflow file to identify the storefront ID?

```
# Don't change the line below!
#! oxygen_storefront_id: 1000000001
```

This makes it impossible to deploy to multiple storefronts from the same workflow. Also, it is very obscure and easy to break.

Is there a specific reason to not simply pass the storefront id as normal parameter? (or just derive it from the deployment token)

```
- name: Build and Publish to Oxygen
  id: deploy
  uses: shopify/oxygenctl-action@v4
  with:
    storefront_id: 1000000001
    oxygen_deployment_token: ${{ secrets.OXYGEN_DEPLOYMENT_TOKEN_10000000001 }}
    build_command: 'HYDROGEN_ASSET_BASE_URL=$OXYGEN_ASSET_BASE_URL npm build'
```

Bonus points:
- It would be nice not to tightly couple the branch to the environment, but to enable us to deploy to two separate environments from the same branch.

For context, here is what we want to do (optimally in a single workflow):

1. Merge code into main branch
2. Deploy main branch to staging environment
3. Automatically test staging environment
4. If green, deploy main branch to production environment

This is impossible right now, since each branch is tied to an environment and each workflow file is tied to a single storefront.
