### ISSUE TITLE
Oxygen cli metadata flags don't work

### ISSUE THREAD

**Issue by irisrumtub** [Shopify/oxygenctl-action#82]
As it is said in [the instruction](https://socket.dev/npm/package/@shopify/oxygen-cli) we can supply additional options to oxygen-cli like
```
--metadataDescription : A brief description of the deployment, typically the commit message associated with the changes being deployed.
--metadataUrl : URL that links to the deployment.
--metadataUser : User that initiated the deployment.
--metadataVersion : A version identifier for the deployment.
```
and it is said that these options will pop up in Shopify Admin, and they don't. Am i doing something wrong?
```yaml
# Don't change the line below!
#! oxygen_storefront_id: 1000008763

name: Storefront 1000008763
on: [push]

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    name: Deploy to Oxygen
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          check-latest: true

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm install

      - name: Check Oxygen version
        id: check_version
        shell: 'bash'
        run: |
          TOKEN="${{ secrets.OXYGEN_DEPLOYMENT_TOKEN_1000008763 }}"
          echo "::add-mask::$TOKEN"

          if [[ "${TOKEN}" == *":"* ]]; then
            echo "Multi token"
            IFS=':' read -ra token_list <<< "${TOKEN}"
            token=${token_list[1]}
            echo "::add-mask::$token"
            echo "token=$token" >> $GITHUB_OUTPUT
          else
            if [[ "${TOKEN}" =~ ^[A-Za-z0-9+/]+[=]{0,2}$ ]]; then
              echo "Token is in V2 format"
              echo "token=${TOKEN}" >> $GITHUB_OUTPUT
            else
              echo "Your repository is out of date, please disconnect and reconnect your storefront on Shopify"
              exit 1
            fi
          fi

      - name: Build and Publish to Oxygen
        shell: 'bash'
        id: 'oxygen-cli-action'
        env:
          NODE_ENV: production
        run: |
          echo "Deploying to Oxygen..."
          build_command_filtered=$(echo 'HYDROGEN_ASSET_BASE_URL=$OXYGEN_ASSET_BASE_URL npm run build' | sed 's/HYDROGEN_ASSET_BASE_URL=$OXYGEN_ASSET_BASE_URL //g')
          oxygen_command="npm exec --package=@shopify/oxygen-cli@3.1.1 -- oxygen-cli oxygen:deploy \
                --assetsFolder=dist/client \
                --workerFolder=dist/worker \
                --verificationMaxDuration=180 \
                --metadataUrl=https://example.com/ \
                --metadataDescription=example \
                --metadataUser=exampleUser \
                --metadataVersion=exampleVersion \
                --token=${{ steps.check_version.outputs.token }}"

          output=$($oxygen_command --buildCommand="${build_command_filtered}")
          echo "preview link is $output"
          exit_code=$?

          if [ $exit_code -ne 0 ]; then
            exit $exit_code
          fi

```
